apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-exporter
  labels:
    app: hostname-exporter
  namespace: hostname-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname-exporter
  template:
    metadata:
      labels:
        app: hostname-exporter
    spec:
      containers:
      - name: hostname-exporter
        image: eugenebad/hostname-exporter:0.0.1a
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 80m
            memory: 80Mi
        ports:
        - containerPort: 9090
          name: http
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
# https://kubernetes.io/docs/concepts/workloads/pods/downward-api/
# https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/