apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostname-exporter
  namespace: hostname-exporter
spec:
  rules:
  - host: hostname-exporter.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hostname-exporter
            port:
              number: 9090
